spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
      # https://github.com/spring-projects/spring-data-jpa/issues/2717#issuecomment-1336159936
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
    # https://habr.com/ru/post/440734/
    open-in-view: false
  datasource.url: jdbc:h2:mem:restaurant_voting;DB_CLOSE_ON_EXIT=FALSE

  output.ansi.enabled: always
  main.banner-mode: off
  jackson.visibility:
    field: any
    setter: none
    getter: none
    is-getter: none
    creator: none
#logging.level.org.springframework:
#  orm.jpa.JpaTransactionManager: DEBUG
#  security: DEBUG