spring:
  profiles:
    default: dev
  sql.init.mode: always
  jpa:
    properties:
      # https://github.com/spring-projects/spring-data-jpa/issues/2717#issuecomment-1336159936
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    defer-datasource-initialization: true
    # https://habr.com/ru/post/440734/
    open-in-view: false
  output.ansi.enabled: always
  main.banner-mode: off
  jackson.visibility:
    field: any
    setter: none
    getter: none
    is-getter: none
    creator: none
server.servlet.encoding:
  charset: UTF-8
  enabled: true
  force: true
# https://github.com/springdoc/springdoc-openapi/issues/682#issuecomment-1082687594
springdoc.swagger-ui.defaultModelsExpandDepth: -1

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:h2:./res/restaurant_voting
    username: sa
    password: change_me
  jpa:
    hibernate.ddl-auto: update
logging:
  file.name: ./res/restaurant_voting.log
  pattern.dateformat: yyyy-MM-dd HH:mm:ss
server.port: 80

---
spring:
  config.activate.on-profile: dev, test
  datasource.url: jdbc:h2:mem:restaurant_voting
  jpa:
    hibernate.ddl-auto: create-drop
    properties:
      hibernate.format_sql: true
    show-sql: true
server.port: 8080